version: '1'

services:
  auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7779:3002
    networks:
      net_con:
        ipv4_address: 10.5.0.5

networks:
  net_con:
    external:
      name: "schedule-network"
